files: ".tf$"
fail_fast: true
minimum_pre_commit_version: "1.15"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.50.0"
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tflint
